
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: app_rails_development
  pool: 5
  username: paliy
  password: 1111


test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: app_rails_test
  pool: 5
  username: paliy
  password: 1111

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: app_rails_production
#   pool: 5
#   username: app_rails
#   password:
